Lesson 10 content
sensu/sensu-enterprise-workshop pull request #94
Opened 2021-10-25 21:32 UTC by calebhailey

New "intro to silencing" content.

2021-10-25 23:29 UTC, thoward requested changes

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +You will learn how to target individual incidents on a single host, specific incidents spanning multiple hosts, and even bulk silencing all incidents across multiple hosts.
"even bulk silencing" => "bulk silence"

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +This lesson is intended for operators of Sensu, and assumes you have [set up a local workshop environment][setup_workshop].
Add a line break before this sentence.

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +Sensu’s silencing capability allows you to suppress event handler execution on an ad hoc basis so you can plan maintenance and reduce alert fatigue.
"ad hoc" => "ad-hoc"

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +Keeping those alerts in check so as to avoid "alert fatigue" is a top priority
Missing period at the end of the sentence.

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +Once Sensu alerts us to an incident that requires further investigation, we can surpress subsequent notifications using [Silences][silencing-docs].
"surpress" => "suppress"

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +Sensu’s silencing capability allows you to suppress event handler execution on an ad hoc basis so you can plan maintenance and reduce alert fatigue.
"Sensu's silencing capability" => "Silencing"

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +Silences are created on an ad hoc basis using `sensuctl`, the Sensu Silenced API, or the Sensu web app.
We just said "ad hoc" two sentences ago, so I think we can omit it here. Also remove unnecessary "Sensu"s.

"Silences are created using `sensuctl`, the Silenced API, or the web app."

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +Some popular use cases for silencing include alert acknowledgement, and overall reduction of alert fatigue.
"popular"=>"common"

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +Since you are the first person to respond to the incident, you want to acknowledge the incident and configure Sensu to disable alerts for the next hour minutes, or until the service is restored (whic
"next hour minutes" ? Next hour? Next 30 minutes?

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +To accomplish this we will configure a silence to suppress an alert (i.e. disabling event processing).
remove "i.e."

"To accomplish this we will configure a silence to disabling event processing suppress the alert."

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +We'll use `sensuctl` to configure silencing in this lesson.
I wouldn't bother mentioning that silences can be done from the web app because we haven't yet introduced it yet, so it's kind of non-sequitur.

I think we can delete both of these sentences.

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +   _NOTE: If you see an error like `curl: (7) Failed to connect to localhost port 9001: Connection refused` it may be that Docker assigned a different port to your demo app container.
Insert line break before this note paragraph, and also indent it with `>` char

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +   In a typical scenario you might silence alerts for an hour or more while you investigate an incident.
"typical scenario" => "real-world scenario"

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +   Wait until the silence expires – when alerts appear in Mattermost again – then move on to the next exercise.
avoid em dash interjections: 

"Wait until the silence expires, and alerts start appearing in Mattermost again, then move on to the next exercise."

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +   > - Providing a check name (`Check: app-health`) means the silence will only apply to events from the app-health check
Use code symbol notion for `app-health`

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +These configuration parameters offer
Line break before this list lead-in.

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +These configuration parameters offer
Change language from "offer" to "what you can do with it"

"You can configure these in the following ways:"

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +- Silencing a specific check on a specific entity:
Change the verb form here to "Silence" vs "Silencing" on all three list items.

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +You are responding to an incident or managing a maintenance operation involving multiple nodes.
Add a little more to this scenario.
"You want to silence all the nodes at once instead of having to silence each one individually."

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +To accomplish this we will configure a silence to suppress multiple alerts (i.e. disabling event processing).
remove "i.e." section. by this point in the document they should be very clear on what silencing does.

We should explain the mechnism of action here. 

"To accomplish this we will configure a silence using a wider subscription which will silence events coming from all subscribed hosts, instead of just one specific host."

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +We'll use `sensuctl` to configure silencing in this lesson.
Remove these two sentences (see prev comment).

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +   ? Subscription: entity:workshop_app_1
This should be `? Subscription: workshop`

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +   As soon as you create this silence, the alerts in Mattermost should be surpressed for 2 minutes.
Remove "As soon as you create this silence, "

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +   Wait until the silence expires – when alerts appear in Mattermost again – then move on to the next exercise.
Change language here to match previous comment.

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +Scheduled maintenance window is a silence that starts and ends in the future.
"A scheduled maintenance window..."

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +   Get the current time in RFC3339 or RFC8601 format.
Link to RFCs... 
https://datatracker.ietf.org/doc/html/rfc3339
https://datatracker.ietf.org/doc/html/rfc8601

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +   Let's use the `sensuctl silenced create` to create a silencing rule for a scheduled maintenance window.
"the `sensuctl silenced create` **command**"

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +   _NOTE: Please modify the begin time to be 2-3 minutes in the future; the macOS `time` utility isn't RFC compliant, so you'll need to add a colon to the timezone offset (e.g. `-07:00` instead of `-
line break before this note.

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +In this lesson we explored different ways to suppress event handling in Sensu Go and covered the popular use cases for [Sensu Silences][silencing-docs].
"the popular" => "some common"

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +Keep reading to learn about additional use cases for Sensu Silences.
strike, unnecessary

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +Scheduled maintenance is a useful practice when a particular maintenance window requires human interaction because human involvement generally has to be coordinated/scheduled in advance.
"requires human interaction because **that** generally"

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +Once the automated maintenace task is completed, the silence can be deleted.
typo "maintenance"

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +This practice of integrating automation tools with Sensu is often referred to as "maintenance mode".
line break before this line.

2021-10-25 23:29 UTC, thoward commented on lessons/operator/10/README.md
> +You can also configure silences from the Sensu Go web app, which we'll introduce in [Lesson 11][lesson-11].
Missing link reference at the bottom.

2021-10-25 23:32 UTC, calebhailey commented on lessons/operator/10/README.md
> +You will learn how to target individual incidents on a single host, specific incidents spanning multiple hosts, and even bulk silencing all incidents across multiple hosts.
👍

2021-10-25 23:32 UTC, calebhailey commented on lessons/operator/10/README.md
> +This lesson is intended for operators of Sensu, and assumes you have [set up a local workshop environment][setup_workshop].
👍

2021-10-25 23:33 UTC, calebhailey commented on lessons/operator/10/README.md
> +Sensu’s silencing capability allows you to suppress event handler execution on an ad hoc basis so you can plan maintenance and reduce alert fatigue.
👍

2021-10-25 23:33 UTC, calebhailey commented on lessons/operator/10/README.md
> +Keeping those alerts in check so as to avoid "alert fatigue" is a top priority
👍

2021-10-25 23:33 UTC, calebhailey commented on lessons/operator/10/README.md
> +Once Sensu alerts us to an incident that requires further investigation, we can surpress subsequent notifications using [Silences][silencing-docs].
👍

2021-10-25 23:34 UTC, calebhailey commented on lessons/operator/10/README.md
> +Keep reading to learn about additional use cases for Sensu Silences.
👍

2021-10-25 23:34 UTC, calebhailey commented on lessons/operator/10/README.md
> +Scheduled maintenance is a useful practice when a particular maintenance window requires human interaction because human involvement generally has to be coordinated/scheduled in advance.
👍

2021-10-25 23:34 UTC, calebhailey commented on lessons/operator/10/README.md
> +Once the automated maintenace task is completed, the silence can be deleted.
👍

2021-10-25 23:35 UTC, calebhailey commented on lessons/operator/10/README.md
> +This practice of integrating automation tools with Sensu is often referred to as "maintenance mode".
👍

2021-10-25 23:35 UTC, calebhailey commented on lessons/operator/10/README.md
> +You can also configure silences from the Sensu Go web app, which we'll introduce in [Lesson 11][lesson-11].
:+1:

2021-10-25 23:36 UTC, thoward approved these changes

2021-10-25 23:36 UTC, merged

2021-10-25 23:37 UTC, thoward commented
Closes #92

2021-10-26 19:42 UTC, thoward commented on lessons/operator/10/README.md
> +Sensu’s silencing capability allows you to suppress event handler execution on an ad hoc basis so you can plan maintenance and reduce alert fatigue.
👍

2021-10-26 19:46 UTC, thoward commented on lessons/operator/10/README.md
> +Silences are created on an ad hoc basis using `sensuctl`, the Sensu Silenced API, or the Sensu web app.
👍

2021-10-26 19:46 UTC, thoward commented on lessons/operator/10/README.md
> +Some popular use cases for silencing include alert acknowledgement, and overall reduction of alert fatigue.
👍

2021-10-26 19:48 UTC, thoward commented on lessons/operator/10/README.md
> +Since you are the first person to respond to the incident, you want to acknowledge the incident and configure Sensu to disable alerts for the next hour minutes, or until the service is restored (whic
👍

2021-10-26 19:49 UTC, thoward commented on lessons/operator/10/README.md
> +To accomplish this we will configure a silence to suppress an alert (i.e. disabling event processing).
👍

2021-10-26 19:51 UTC, thoward commented on lessons/operator/10/README.md
> +We'll use `sensuctl` to configure silencing in this lesson.
👍

2021-10-26 19:53 UTC, thoward commented on lessons/operator/10/README.md
> +   _NOTE: If you see an error like `curl: (7) Failed to connect to localhost port 9001: Connection refused` it may be that Docker assigned a different port to your demo app container.
👍

2021-10-26 19:53 UTC, thoward commented on lessons/operator/10/README.md
> +   In a typical scenario you might silence alerts for an hour or more while you investigate an incident.
👍

2021-10-26 20:20 UTC, thoward commented on lessons/operator/10/README.md
> +   Wait until the silence expires – when alerts appear in Mattermost again – then move on to the next exercise.
👍

2021-10-26 20:20 UTC, thoward commented on lessons/operator/10/README.md
> +   > - Providing a check name (`Check: app-health`) means the silence will only apply to events from the app-health check
👍

2021-10-26 20:23 UTC, thoward commented on lessons/operator/10/README.md
> +These configuration parameters offer
👍

2021-10-26 20:23 UTC, thoward commented on lessons/operator/10/README.md
> +These configuration parameters offer
👍

2021-10-26 20:24 UTC, thoward commented on lessons/operator/10/README.md
> +- Silencing a specific check on a specific entity:
👍

2021-10-26 20:26 UTC, thoward commented on lessons/operator/10/README.md
> +You are responding to an incident or managing a maintenance operation involving multiple nodes.
👍

2021-10-26 21:02 UTC, thoward commented on lessons/operator/10/README.md
> +To accomplish this we will configure a silence to suppress multiple alerts (i.e. disabling event processing).
👍

2021-10-26 21:02 UTC, thoward commented on lessons/operator/10/README.md
> +We'll use `sensuctl` to configure silencing in this lesson.
👍

2021-10-26 21:02 UTC, thoward commented on lessons/operator/10/README.md
> +   ? Subscription: entity:workshop_app_1
👍

2021-10-26 21:04 UTC, thoward commented on lessons/operator/10/README.md
> +   As soon as you create this silence, the alerts in Mattermost should be surpressed for 2 minutes.
👍

2021-10-26 21:04 UTC, thoward commented on lessons/operator/10/README.md
> +   Wait until the silence expires – when alerts appear in Mattermost again – then move on to the next exercise.
👍

2021-10-26 21:06 UTC, thoward commented on lessons/operator/10/README.md
> +Scheduled maintenance window is a silence that starts and ends in the future.
👍

2021-10-26 21:09 UTC, thoward commented on lessons/operator/10/README.md
> +   Get the current time in RFC3339 or RFC8601 format.
👍

2021-10-26 21:10 UTC, thoward commented on lessons/operator/10/README.md
> +   Let's use the `sensuctl silenced create` to create a silencing rule for a scheduled maintenance window.
👍

2021-10-26 21:10 UTC, thoward commented on lessons/operator/10/README.md
> +   _NOTE: Please modify the begin time to be 2-3 minutes in the future; the macOS `time` utility isn't RFC compliant, so you'll need to add a colon to the timezone offset (e.g. `-07:00` instead of `-
👍

2021-10-26 21:11 UTC, thoward commented on lessons/operator/10/README.md
> +   Wait until the silence expires – when alerts appear in Mattermost again – then move on to the next exercise.
👍